%%
%% Autogenerated by Thrift Compiler (0.9.3)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(models_types).

-include("models_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('Message') ->
  {struct, [{1, string},
          {2, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('Message') ->
  {struct, [{1, undefined, string, 'url', undefined},
          {2, undefined, string, 'payload', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

