{application,thrift,
             [{registered,[]},
              {description,"Thrift utilities for Elixir"},
              {vsn,"1.0.0"},
              {modules,['Elixir.Mix.Tasks.Compile.Thrift',
                        thrift_base64_transport,thrift_binary_protocol,
                        thrift_buffered_transport,thrift_client,
                        thrift_client_util,thrift_disk_log_transport,
                        thrift_file_transport,thrift_framed_transport,
                        thrift_http_transport,thrift_json_parser,
                        thrift_json_protocol,thrift_memory_buffer,
                        thrift_processor,thrift_protocol,
                        thrift_reconnecting_client,thrift_server,
                        thrift_service,thrift_socket_server,
                        thrift_socket_transport,thrift_transport,
                        thrift_transport_state_test]},
              {applications,[kernel,stdlib,elixir]}]}.